# please notice that the id should be continuous
# or recipes won't be loaded correctly
1:
 name: testCraft
 in:
  - itemname:       DIAMOND
    # use enumeration name here, you can reference to bukkit API list
    isMajor:        No
    leastAmount:    2
    base:           1.0
  
  - itemname:       COAL
    isMajor:        No
    leastAmount:    0
    base:           0.1
    formula:        linear
    # formula has these types
    # linear(y = k*x + b), log(y = a*log _b x + c ), expr(y = a*x ^ b + c)
    arg1: 1
    arg2: 0
    arg3: 0
    # arg3 is not used in linear formula
    # the probability will be calculated in this way (for linear formula)
    # Probability = arg1 * amount + arg2
    df: 0
    # domain from
    dt: 64
    # domain to
    
  - itemname:       GOLD_SWORD
    isMajor:     Yes
    leastAmount:    1
    
 out:
  - itemname:       DIAMOND_SWORD
    lore: |
      A kick-ass sword that can kick everyone's ass!
      Maybe...