limit: 300 # seconds
lobby: world
message: 'You have left for too long and was sent back to spawn!'
including-kicks: no
worlds:
  - world_pvp
penalty:
  ground:
    enable: yes
    duration: 60 # seconds
    message: 'You cannot move to another world now'
  clearInventory:
    enable: yes
