name: Arsenal
main: tech.dsstudio.minecraft.arsenal.Main
version: 0.1-INTERNAL
author: dousha99
depend:
  - AbstractRepository
commands:
  ara:
    description: Add the item in hand to repository
    usage: /ara <perm>
    permission: arsenal.add
  ard:
    description: Delete an item from repository
    usage: /ard <perm>
    permission: arsenal.delete
  aro:
    description: Open the arsenal
    usage: /aro
    permission: arsenal.use
  arr:
    description: Reload configuration
    usage: /arr
    permission: arsenal.reload