name: ArmorHide
main: tech.dsstudio.minecraft.armorHide.Main
version: 0.1-INTERNAL
author: dousha99
depend:
  - ProtocolLib
commands:
  ahr:
    description: Reload configuration
    permission: armorhide.reload
  ahon:
    description: Hide your current armor
    permission: armorhide.use
  ahoff:
    description: Reveal your current armor
    permission: armorhide.use
permissions:
  armorhide.reload:
    description: Grants reloading configuration file
    default: op
  armorhide.use:
    description: Grants the usage of hiding armor
    default: op