name: WorldTimer
main: tech.dsstudio.minecraft.worldtimer.Main
version: 0.1-INTERNAL
description: Put a time limit on a stay!
depend:
  - PlayerData
  - PlayerTaskHook

permissions:
  wtexempt:
    description: Self-explanatory
    default: op