name: WorldTimer
main: tech.dsstudio.minecraft.worldtimer.Main
version: 0.2-INTERNAL
description: Put a time limit on a stay!
depend:
  - PlayerData
  - PlayerTaskHook

permissions:
  wt.use:
    description: Allow use of /wt commands
    default: op
  wtexempt:
    description: Self-explanatory
    default: op

commands:
  wt:
    description: WorldTimer controlling command
    usage: /wt <pause|resume> [player=self]
    permission: wt.use