name: HopperScan
main: tech.dsstudio.minecraft.hopperScanner.HopperScanner
version: 0.1-INTERNAL
author: dousha99
commands:
  hscan:
    description: Start a scan
    permission: hscan.do
  hlast:
    description: See last result
    permission: hscan.see
  hreload:
    description: Reload configuration
    permission: hscan.reload
permissions:
  hscan.*:
    description: Grants everything
    children:
      - hscan.do
      - hscan.see
      - hscan.reload
  hscan.do:
    description: Starts a scan
  hscan.see:
    description: See last scan result
  hscan.reload:
    description: Reload plugin configuration