name: DSRuntime
version: 0.1-BLEEDING
main: tech.dsstudio.minecraft.dsrt.ServerRuntime
author: dousha99
commands:
  ls:
    description: List files
  touch:
    description: Create file
  rm:
    description: Delete file
